### PR TITLE
don't bind-mount /etc passwd & group when persistent writes possible, from sylabs 1822

### PR DESCRIPTION
**Pull request by edytuk**
This pulls in sylabs PR

- sylabs/singularity# 1822
 which fixed
- sylabs/singularity# 1812

The original PR description was:
> If all of the following conditions hold —
> 
> * The user inside the container is root
> * The root filesystem is writable
> * The root filesystem is not a tmpfs
> 
> — then writes to `/etc/passwd` or `/etc/group` are possible, and would be expected to persist from build to action stage (run/exec/shell) or across distinct actions (e.g. from one run to the next).
> 
> Under this exact combination of conditions, then, we inhibit bind-mounting modified versions of `/etc/passwd` and `/etc/group` from tmpfs storage into the container.

### CODE REVIEW

**Comment by DrDaveD** [comment]
This is a potential fix for the problem seen in #318.  The problem is that it only covers the writable options that SingularityCE handles and it does not cover additional conditions where Apptainer has a writable container.  It's easy to check for `--writable-tmpfs`, just change the `&& (!` to `||` in the new `addIdentityMount` code (moving the open paren to be before the writableimage check), but it's not easy to tell if an overlay is writable.  [This function](https://github.com/edytuk/apptainer/blob/main/internal/pkg/runtime/engine/apptainer/prepare_linux.go#L1311) calculates it in the `writableOverlay` local variable, but it doesn't save the information and it's a different phase.   I'm pretty sure at least that it runs earlier.  Maybe if the flag gets saved in a new engineconfig variable it could be used later in `addIdentityMount`.

**Comment by DrDaveD** [comment]
> I modified if statement in `addIdentityMount`. Should we try to save `writableOverlay` variable?

Yes I'm afraid that's necessary.

**Comment by edytuk** [comment]
I think that I saved `writableOverlay` variable, but I do not know how to test this

**Comment by DrDaveD** [comment]
Add `|| c.engine.EngineConfig.GetWritableImage()` do the if checks in container_linux.go, then run with `apptainer -v` to see if the Verbose message gets printed.  Do `mkdir /tmp/overlay` and add an action command (i.e. exec, shell, or run) option `--overlay /tmp/overlay`.  With that option, the message should print.  If you add a `:ro` to the end of it, the message should not print.  Outside of `-v` you could also check the output of `mount` inside the container to see if it is mounting /etc/passwd and /etc/group.

**Comment by edytuk** [comment]
Verbose message does not appear. I was running these commands without and with sudo:
apptainer -v exec docker://centos:7 bash
apptainer -v exec --overlay /tmp/overlay docker://centos:7 bash
apptainer -v exec --overlay /tmp/overlay:ro docker://centos:7 bash

**Comment by DrDaveD** [comment]
Oh but after reading the CHANGELOG entry in #318, I see that removing that previous code was the point of that PR, in order to change what happens to the passwd file when running under root or fakeroot.  So we still do need your changes to writableOverlay so we can still make those changes take effect whenever the container is readonly.  I will try your commit from this PR over in #318 instead.

**Pull request closed without merging**
