### PR TITLE
oci: Switch to runc for OCI commands, from sylabs 602

### PR DESCRIPTION
**Pull request by edytuk**
675, 765, 769, 821, 860 (part of e2e/suite.go), 1047, 1048, 1086

singularity-admindocs:
51, 52

singularity-userdocs:
92 edytuk/apptainer-userdocs#15

This pulls in sylabs PR

- sylabs/singularity#602
which fixed
- sylabs/singularity#595

The original PR description was:
> This is an initial step in removing the native Singularity OCI runtime, which is a wrapper around instance functionality, and integrating runc. This PR is not the completion of this work, but attempts to do enough to satisfy the E2E tests as a first step.
> 
> * Remove the internal/pkg/runtime/oci engine
> * Modify the `singularity oci` commands to use `runc` as the OCI runtime, and `conmon` as a shim for the detached lifecycle.
> * Add `third_party/conmon` as a submodule, which will be used to build and install conmon to `libexec/conmon` unless `--without-conmon` is specified. If `--without-conmon` is specified, Singularity will search `PATH` for conmon, which must be >=2.0.24.
> 
> 
> Current limitations of this PR:
> 
> * `runc` is always required to be on `PATH` as pre-installed dependencies.
> * Terminal handling is incomplete. We need to track whether a container's `config.json` sets `terminal: true` and handle stdio, refresh, resize correctly on `oci attach`.
> * State tracking is rudimentary, using files / links under `.singularity/oci` in a similar approach to the instance / old oci runtime.
> * We are implementing `singularity oci run` by directly calling `runc` rather than using `conmon` at present, so state tracking / bundle locking is not the same / complete.
> * The code needs to be refactored for DRY, and to break out the OCI operations from the CLI layer, for re-use in further OCI runtime work.
> * `--sync-socket`, `--empty-process`, and  `--timeout` flags have been removed. `--empty-process` and `--timeout` may be useful to re-add.
> * Logging does not match with the stated formats of the `--log-file` flag.
> 
> Create and attach code is based on that in podman, with the license noted. There are some conmon related utility functions that have been brought in from files in the podman code, to avoid importing large parts of that project. The 3rd party licenses file has been updated accordingly.

### CODE REVIEW

**Comment by DrDaveD** [comment]
This one may take a while to make a decision on, I am bringing it up in a discussion

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Please take out the [oci: add conmon to build via submodule](https://github.com/edytuk/apptainer/pull/65/commits/a674bb6b42e763ce734bc283366ea51aac3f4b26) commit and rebase on the current main.

**Comment by DrDaveD** [comment]
I noticed some tests had failed and that the base branch was still set to `main` so I changed the base branch to `oci-action` and asked to have the checks re-run.

**Comment by DrDaveD** [comment]
There's remaining problems, I'll leave them to you.

**Comment by edytuk** [comment]
Now tests are green

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
